// <auto-generated />
namespace StackOverFlowProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class QuestionsRequiredFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QuestionsRequiredFields));
        
        string IMigrationMetadata.Id
        {
            get { return "202105082144460_QuestionsRequiredFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
